version: '2'
services:
  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /etc/oecpreport/conf.ini:/etc/oecpreport/conf.ini
      - /home/oecp-report:/home/oecp-report
  redis:
    image: "redis:alpine"
    ports:
      - "6378:6379"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
